# Generated by Django 4.2.15 on 2024-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactM',
            fields=[
                ('ied', models.CharField(auto_created=True, max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('enqtxt', models.CharField(max_length=500)),
                ('regdate', models.DateTimeField()),
            ],
        ),
    ]
