# Generated by Django 5.1.2 on 2024-11-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number', models.BigIntegerField()),
            ],
        ),
    ]
