# Generated by Django 5.1.2 on 2024-11-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dash', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='number',
            field=models.BigIntegerField(default=0),
        ),
    ]
